### ISSUE TITLE
Calculator does not support matrices

### ISSUE THREAD

**Issue by wenkesj** [austinkelleher/clickjacker-chrome-extension#1]
Calculator doesn't support matrix operations or fast fourier transforms. I for one would know that this is a `clickjacking` extension

**Comment by wenkesj** [comment]
When will I see this update?

**Comment by austinkelleher** [comment]
Thanks for opening this issue. We are currently working on N64 support, which will include quantum mechanical operations. During the process we will be implementing the aforementioned matrix operations. PR's welcome.

**Comment by wenkesj** [comment]
- [x] N64 support
- [x] Goteem GIF support, TBD?

Thanks,
Phil

**Comment by wenkesj** [comment]
Thanks for the feedback.

I love you,
Happy Birthday 😀
